name: Reusable Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      runner_tag:
        required: true
        type: string
      DB_HOST:
        type: string
      DB_PORT:
        type: string
      DB_USERNAME:
        type: string
      DB_DATABASE:
        type: string
      NODE_ENV:
        type: string
    secrets:
      EC2_HOST:
        required: false
      EC2_USER:
        required: false
      EC2_SSH_KEY:
        required: false
      DB_PASSWORD:
        required: false
      AUTH_SECRET:
        required: false
      SENTRY_AUTH_TOKEN:
        required: true
      SENTRY_DSN:
        required: true

jobs:
  build-test-deploy:
    runs-on: [self-hosted, '${{ inputs.runner_tag }}']
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker

      - name: Run Tests
        uses: docker/build-push-action@v5
        with:
          context: .
          target: test
          push: false
          load: false

      - name: Build Production Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          no-cache: true
          tags: my-app:latest
          secrets: |
            sentry_token=${{ secrets.SENTRY_AUTH_TOKEN }}

      # 4. DEPLOY (Only happens if build passes)
      - name: Create .env file
        run: |
          touch .env
          echo "NODE_ENV=${{ vars.NODE_ENV }}" >> .env
          echo "DB_HOST=${{ vars.DB_HOST }}" >> .env
          echo "DB_PORT=${{ vars.DB_PORT }}" >> .env
          echo "DB_USERNAME=${{ vars.DB_USERNAME }}" >> .env
          echo "DB_DATABASE=${{ vars.DB_DATABASE }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "AUTH_SECRET=${{ secrets.AUTH_SECRET }}" >> .env
          echo "SENTRY_DSN=${{ secrets.SENTRY_DSN }}" >> .env

      - name: Local Deploy
        run: |
          docker compose down --remove-orphans
          docker compose up -d --force-recreate
