name: Reusable Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      runner_tag:
        required: true
        type: string
      DB_HOST:
        type: string
      DB_PORT:
        type: string
      DB_USERNAME:
        type: string
      DB_DATABASE:
        type: string
      NODE_ENV:
        type: string
    secrets:
      EC2_HOST:
        required: false
      EC2_USER:
        required: false
      EC2_SSH_KEY:
        required: false
      DB_PASSWORD:
        required: false
      AUTH_SECRET:
        required: false
      SENTRY_AUTH_TOKEN:
        required: true
      SENTRY_DSN:
        required: true

jobs:
  cleanup:
    runs-on: [self-hosted, '${{ inputs.runner_tag }}']
    steps:
      - name: Smart Disk Cleanup
        run: |
          # We prune images older than 24h so we don't delete the cache we just used
          docker image prune -af --filter "until=24h"
          # We don't prune the builder here because that would delete our cache!

  test:
    needs: cleanup
    runs-on: [self-hosted, '${{ inputs.runner_tag }}']
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests with Cache
        uses: docker/build-push-action@v5
        with:
          context: .
          target: test
          push: false
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

  build:
    needs: test
    runs-on: [self-hosted, '${{ inputs.runner_tag }}']
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker

      - name: Build Production Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: my-app:latest
          secrets: |
            sentry_token=${{ secrets.SENTRY_AUTH_TOKEN }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  deploy:
    needs: build
    runs-on: [self-hosted, '${{ inputs.runner_tag }}']
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - name: Local Deploy
        run: |
          # No cache needed here, it just uses the 'my-app:latest' image 
          # loaded into the Docker engine by the 'build' job.
          docker compose up -d --force-recreate
