name: Reusable Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: false
        type: string
      runner_tag:
        required: false
        type: string
      DB_HOST:
        type: string
      DB_PORT:
        type: string
      DB_USERNAME:
        type: string
      DB_DATABASE:
        type: string
      NODE_ENV:
        type: string
    secrets:
      EC2_HOST:
        required: false
      EC2_USER:
        required: false
      EC2_SSH_KEY:
        required: false
      DB_PASSWORD:
        required: false
      AUTH_SECRET:
        required: false
      SENTRY_AUTH_TOKEN:
        required: true
      SENTRY_DSN:
        required: true

jobs:
  # JOB 1: CLEANUP
  cleanup:
    runs-on: [self-hosted, '${{ inputs.runner_tag }}']
    steps:
      - name: Smart Disk Cleanup
        run: |
          docker image prune -af --filter "until=24h"

          docker builder prune -af --filter "until=24h"

          docker container prune -f

  # JOB 2: Build + Test
  build:
    needs: cleanup
    runs-on: [self-hosted, '${{ inputs.runner_tag }}']
    environment: ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (tests inside)
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: my-app:latest
          secrets: |
            sentry_token=${{ secrets.SENTRY_AUTH_TOKEN }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Promote Docker cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  # JOB 4: DEPLOY
  deploy:
    needs: build
    runs-on: [self-hosted, '${{ inputs.runner_tag }}']
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - name: Create .env file
        run: |
          echo "NODE_ENV=${{ vars.NODE_ENV }}" > .env
          echo "DB_HOST=${{ vars.DB_HOST }}" >> .env
          echo "DB_PORT=${{ vars.DB_PORT }}" >> .env
          echo "DB_USERNAME=${{ vars.DB_USERNAME }}" >> .env
          echo "DB_DATABASE=${{ vars.DB_DATABASE }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "AUTH_SECRET=${{ secrets.AUTH_SECRET }}" >> .env
          echo "SENTRY_DSN=${{ secrets.SENTRY_DSN }}" >> .env

      - name: Local Deploy
        run: |
          docker compose up -d --force-recreate
